export type Locale = 'en' | 'es' | 'pt';

export type TranslationDict = {
  siteTitle: string;
  siteTagline: string;
  home: string;
  language: string;
  allRightsReserved: string;
  colorPicker: string;
  paletteExtractor: string;
  gradientGen: string;
  colorSchemes: string;
  hex: string;
  rgb: string;
  hsl: string;
  copy: string;
  copied: string;
  uploadImage: string;
  extractPalette: string;
  colorsFound: string;
  dropImage: string;
  gradient: string;
  direction: string;
  addColor: string;
  randomPalette: string;
  // Color schemes
  harmony: string;
  complementary: string;
  analogous: string;
  triadic: string;
  tetradic: string;
  splitComplementary: string;
  materialPalette: string;
  appleColors: string;
  accessibility: string;
  contrastRatio: string;
  textOnColor: string;
  pass: string;
  fail: string;
  largeText: string;
  normalText: string;
  systemColors: string;
  primary: string;
  secondary: string;
  tertiary: string;
};
